#!/bin/bash
#
# editcomments - edit comments in photogallery gallery
#
# Copyright (C) 2008-2026  Christian Garbs <mitch@cgarbs.de>
# licensed under GNU GPL v2 or later
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

VERSION=git
TEMP1=$(mktemp)
TEMP2=$(mktemp)

# version number
if [ "$1" = "-v" ] || [ "$1" = "--version" ] ; then
    echo "editcomments (version ${VERSION})"
    exit 1
fi

# help text
if [ -z "${*}" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then
    echo "Usage: editcomments [ -v | --version | -h | --help ] FILE..."
    echo "Edit image comments for photogallery galleries."
    echo "  -h, --help       show this help "
    echo "  -v, --version    show version number"
    exit 1
fi

# collect files and comments
for FILE in "${@}"; do
    if [ -e "$FILE" ] ; then
	echo "====$FILE"
	[ -e "$FILE.text" ] && cat "$FILE.text"
    fi
done > "$TEMP1"

# edit list
if [ ! -s "$TEMP1" ] ; then
    echo "no files found"
    exit 1
fi
"$EDITOR" "$TEMP1"

# add end mark
echo "====" >> "$TEMP1"

# split list into files
touch "$TEMP2"
while read -r LINE ; do

        if [ "${LINE:0:4}" = '====' ] ; then
	    rm -f "$FILENAME"
	    [ -s "$TEMP2" ] && mv "$TEMP2" "$FILENAME"
	    touch "$TEMP2"
		
	    FILENAME="${LINE:4}"
	    if [ ! -e "${FILENAME}" ] && [ "$FILENAME" ] ; then
		echo "skipping file $FILENAME: does not exist"
	    fi
	    FILENAME="${FILENAME}.text"
	else
	    echo "$LINE" >> "$TEMP2"
	fi

done < "$TEMP1"

rm "$TEMP1" "$TEMP2"
