#!/bin/bash
#
# 2008 (c) by Christian Garbs <mitch@cgarbs.de>
#
# add exif tags for photogallery gallery
# licensed under GNU GPL v2
#

VERSION=git

# version number
if [ "$1" = "-v" -o "$1" = "--version" ] ; then
    echo "exif2text (version ${VERSION})"
    exit 1
fi

for FILE in "${@}"; do

    exiftool -q -s -s -FocalLength -ApertureValue -ExposureTime -ISO "${FILE}" | 
    (
	while read KEY VAL; do
	    [ "${KEY}" = 'FocalLength:'   ] && F="${VAL}"
	    [ "${KEY}" = 'ApertureValue:' ] && A="${VAL}"
	    [ "${KEY}" = 'ExposureTime:'  ] && E="${VAL}"
	    [ "${KEY}" = 'ISO:'           ] && I="${VAL}"
	done
    
	SEP=''
	[ "$F" ] && echo -n "f=${F}" && SEP=', '
	[ "$E" ] && echo -n "${SEP}" && echo -n "${E}s" && SEP=', '
	[ "$A" ] && echo -n "${SEP}" && echo -n "1:${A}" && SEP=', '
	[ "$I" ] && echo -n "${SEP}" && echo -n "ISO ${I}" && SEP=', '
	[ "$SEP" ] && echo
    ) >> "${FILE}.text"
    
    echo -n "."
done
echo
