#!/bin/bash
#
# exif2text - add exif tags to photogallery gallery
#
# Copyright (C) 2008,2009  Christian Garbs <mitch@cgarbs.de>
# licensed under GNU GPL v2 or later
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

VERSION=git

# version number
if [ "$1" = "-v" -o "$1" = "--version" ] ; then
    echo "exif2text (version ${VERSION})"
    exit 1
fi

# help text
if [ "${*}" = "" -o "$1" = "-h" -o "$1" = "--help" ] ; then
    echo "Usage: exif2text [ -v | --version | -h | --help ] FILE..."
    echo "Add exif tags to photogallery gallery comments."
    echo "  -h, --help       show this help "
    echo "  -v, --version    show version number"
    exit 1
fi

for FILE in "${@}"; do

    exiftool -q -s -s -FocalLength -ApertureValue -ExposureTime -ISO "${FILE}" | 
    (
	while read KEY VAL; do
	    [ "${KEY}" = 'FocalLength:'   ] && F="${VAL}"
	    [ "${KEY}" = 'ApertureValue:' ] && A="${VAL}"
	    [ "${KEY}" = 'ExposureTime:'  ] && E="${VAL}"
	    [ "${KEY}" = 'ISO:'           ] && I="${VAL}"
	done
    
	SEP=''
	[ "$F" ] && echo -n "f=${F}" && SEP=', '
	[ "$E" ] && echo -n "${SEP}" && echo -n "${E}s" && SEP=', '
	[ "$A" ] && echo -n "${SEP}" && echo -n "1:${A}" && SEP=', '
	[ "$I" ] && echo -n "${SEP}" && echo -n "ISO ${I}" && SEP=', '
	[ "$SEP" ] && echo
    ) >> "${FILE}.text"
    
    echo -n "."
done
echo
