#!/bin/bash
#
# 2008 (c) by Christian Garbs <mitch@cgarbs.de>
#
# add exif tags for photogallery gallery
# licensed under GNU GPL v2
#

VERSION=git

# version number
if [ "$1" = "-v" -o "$1" = "--version" ] ; then
    echo "exif2text (version ${VERSION})"
    exit 1
fi

# help text
if [ "${*}" = "" -o "$1" = "-h" -o "$1" = "--help" ] ; then
    echo "Usage: exif2text [ -v | --version | -h | --help ] FILE..."
    echo "Add exif tags to photogallery gallery comments."
    echo "  -h, --help       show this help "
    echo "  -v, --version    show version number"
    exit 1
fi

for FILE in "${@}"; do

    exiftool -q -s -s -FocalLength -ApertureValue -ExposureTime -ISO "${FILE}" | 
    (
	while read KEY VAL; do
	    [ "${KEY}" = 'FocalLength:'   ] && F="${VAL}"
	    [ "${KEY}" = 'ApertureValue:' ] && A="${VAL}"
	    [ "${KEY}" = 'ExposureTime:'  ] && E="${VAL}"
	    [ "${KEY}" = 'ISO:'           ] && I="${VAL}"
	done
    
	SEP=''
	[ "$F" ] && echo -n "f=${F}" && SEP=', '
	[ "$E" ] && echo -n "${SEP}" && echo -n "${E}s" && SEP=', '
	[ "$A" ] && echo -n "${SEP}" && echo -n "1:${A}" && SEP=', '
	[ "$I" ] && echo -n "${SEP}" && echo -n "ISO ${I}" && SEP=', '
	[ "$SEP" ] && echo
    ) >> "${FILE}.text"
    
    echo -n "."
done
echo
