#!/bin/bash
#
# photogallery - simple selfcontained static photogallery script
#
# Copyright (C) 2007-2026  Christian Garbs <mitch@cgarbs.de>
# licensed under GNU GPL v2 or later
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# External commands needed:
#    - convert(1) from ImageMagick
#    - dcraw(1) (only if you want to convert RAW files)
#    - mplayer(1) (for conversion of videos)
#    - sed(1)

IFS='' read -r -d '' SHORTHELP << EOF
Usage: photogallery [ OPTION... ] [ gallerytitle ]
Generate a simple image gallery.

OPTIONs:
  -h, --help       show usage
  -H, --longhelp   show extended help
  -v, --version    show version number
  -d, --dark       use default dark CSS
  -l, --light      use defaull light CSS
EOF

IFS='' read -r -d '' LONGHELP << EOF
Run this script inside a directory with pictures.
It will generate a subfolder \`%%SUBDIR%%' with some thumbnails
and an HTML index file named \`%%INDEX%%'.
The gallery title is optional and defaults to the current directory
name.
To describe a gallery, put a file named README into the directory.
It will be included in the generated HTML index file.
To describe an image some.jpeg, put a file named some.jpeg.text into
the same directory (see \`editcomments' script).

Already existing thumbnails will not be overwritten.

Basic CSS support is available:
The environment variables \$GALLERYCSS and \$THUMBCSS are evaluated
and directly included in the generated HTML files.  Tag IDs are
#nav, #pic, #sig and #txt.  In a gallery, you can also set img.txt
and img.notxt to distinguish pictures with comments from those
without.

Example:
GALLERYCSS="#txt,#sig{float:right;}#pic{clear:left;}#nav{float:left;}"

Use -d or -l to select default values for dark or light css.

To generate lots of galleries in subdirectories use this (only
works if there are no line breaks in your directory names):

  find . -depth \! -name .\* -type d | \\
  while read DIR; do ( echo "\$DIR"; cd "\$DIR"; photogallery ) ; done

If you want to browse your galleries directly from your filesystem
without a webserver, you have to run this twice so that all links
are generated properly!

To change some of the defaults, edit the \`photogallery' script.
Instructions are at the top of the file.
EOF

#### configuration

CHARSET=UTF-8
DATELANG=C
MEDIUM=640x640
SMALL=20%
SUBDIR=.webthumbs
INDEX=index.html

VERSION=1.30+git

#### css defaults

FOLDER_ICON_DATA="data:image/png;base64,\
iVBORw0KGgoAAAANSUhEUgAAABAAAAAMAgMAAAAWidUSAAAADFBMVEXXCAj//wz///8AAADs2EAs\
AAAAAXRSTlMAQObYZgAAAAFiS0dEAIgFHUgAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfY\
BhEUKReJ5uA4AAAAHXRFWHRDb21tZW50AENyZWF0ZWQgd2l0aCBUaGUgR0lNUO9kJW4AAAAhSURB\
VAjXY+D/z8DAYLXqAAOD/f//fxiuhoaGE0OAFAMAqAYX1VxCxV4AAAAASUVORK5CYII="

GALLERYCSS_LIGHT="#nav>a{padding-left:20px;background:url(${FOLDER_ICON_DATA})
center left no-repeat;}
#txt,#sig{float:right;}
#pic{clear:left;}
#nav{float:left;}
img{margin:0.5em;box-shadow: 0.2em 0.2em 0.3em gray;border-radius: 0.1em;}
img.txt{border-bottom:solid royalblue 0.3em;}"

THUMBCSS_LIGHT=""

GALLERYCSS_DARK="#nav>a{padding-left:20px;background:url(${FOLDER_ICON_DATA})
center left no-repeat;}
#txt,#sig{float:right;}\
#pic{clear:left;}\
#nav{float:left;}\
img{margin:0.5em;box-shadow: 0.2em 0.2em 0.3em #000;border-radius: 0.1em;}\
img.txt{border-bottom:solid #99f 0.3em;}
html{background-color:#222;color:#ddd;}
a{color:#99f;}"

THUMBCSS_DARK="html{background-color:#222;color:#ddd;}
a{color:#99f;}"

#### function declarations

status() {
    echo "$@" 1>&2
}

uriencode()
{
    local INPUT OUTPUT CHAR POS LANG
    INPUT="$1"
    LANG=C

    for (( POS=0 ; POS < ${#INPUT} ; POS++ )); do
	CHAR="${INPUT:$POS:1}"
	case "${CHAR}" in
	    [0-9a-zA-Z\(\)\'*~\\!./_-])
                OUTPUT="${OUTPUT}${CHAR}"
		;;
	    *)
                ORD=$(( $(printf '%d' "'$CHAR") & 255 ))
		OUTPUT="${OUTPUT}%$(printf %0x ${ORD})"
		;;
        esac
    done

    URIENCODE="${OUTPUT}"
}

html_head() {
    CSS="$1"
    echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml1.dtd">'
    echo '<html><head>'
    echo "<title>$TITLE</title>"
    if [ "$CSS" ] ; then
	echo '<style type="text/css"><!--'
	echo "$CSS"
	echo '--></style>'
    fi
    echo "<meta http-equiv=\"content-type\" content=\"text/html; charset=${CHARSET}\" />"
    echo '</head>'
}

html_foot() {
    echo '<p id="sig"><small><small><i>generated on ' "$(LC_ALL=${DATELANG} date)" 'by <a href="http://www.cgarbs.de/photogallery.en.html">photogallery '"v${VERSION}</a></i></small></small></p></body></html>"
}

#### main script

# argument parsing

for ARG in "$@"; do
    case $ARG in
	
	# version number
	-v|--version)
	    echo "photogallery (version ${VERSION})"
	    exit 0
	    ;;

	# help text
	-h|--help)
	    echo "$SHORTHELP"
	    exit 0
	    ;;
	
	-H|--longhelp)
	    echo "$SHORTHELP"
	    echo "$LONGHELP"
	    exit 0
	    ;;
	
	# default css parameters
	-d|--dark)
	    shift 1
	    GALLERYCSS=$GALLERYCSS_DARK
	    THUMBCSS=$THUMBCSS_DARK
	    ;;

	-l|--light)
	    shift 1
	    GALLERYCSS=$GALLERYCSS_LIGHT
	    THUMBCSS=$THUMBCSS_LIGHT
	    ;;
    esac
done

TITLE=${1:-${PWD##*/}}

# start generation

exec > $INDEX

html_head "$GALLERYCSS"
echo '<body>'

if [ -r "../$INDEX" ] ; then
    uriencode "../$INDEX"
    echo -n "<p id=\"nav\"><a href=\"${URIENCODE}\">[ up ]</a>"
else
    echo -n '<p id="nav"><a href="..">[ up ]</a>'
fi

SUBDIRS=0
for DIR in *; do

    [ -d "$DIR" ] || continue
    [ -r "$DIR" ] || continue
    [ "${DIR:0:1}" = '.' ] && continue

    echo '<br />'
    if [ -r "$DIR/$INDEX" ] ; then
	uriencode "$DIR/$INDEX"
    else
	uriencode "$DIR"
    fi
    echo -n "<a href=\"${URIENCODE}\">$DIR/</a>"

    status -n :
    (( ++SUBDIRS ))

done
echo '</p>'

status -n "$SUBDIRS "

if [ -e README ] ; then
    if [ "$GALLERYCSS" ] ; then
	echo '<div id="txt">'
	cat < README
	echo '</div>'
    else
	echo '<p id="txt">'
	cat < README
	echo '</p>'
    fi
fi

mkdir -p "$SUBDIR" || exit 1

echo '<p id="pic">'

declare -a FILES
for FILE in *; do
    [ -f "$FILE" ] || continue
    [ -r "$FILE" ] || continue
    EXT="${FILE/*.}"

    case "$EXT" in 
	gif|jpeg|jpg|JPG|png|tif|tiff)
	    ;;
	mpg|mpeg|mov|MOV)
	    ;;
	pef|PEF)
	    ;;
	cr2|CR2)
	    ;;
	*)
	    continue
	    ;;
    esac

    FILES+=("$FILE")
done

status -n "${#FILES[*]}>"

for (( IDX=0; IDX < ${#FILES[*]}; IDX++ )) ; do

    FILE="${FILES[${IDX}]}"

    EXT="${FILE/*.}"
    M_INDEX="${FILE}_m.html"
    M_FILE="${FILE}_m.jpg"
    S_FILE="${FILE}_s.jpg"

    if [ ! -s "$SUBDIR/$M_FILE" ] ; then
	case "$EXT" in
	    
	    gif|jpeg|jpg|JPG|png|tif|tiff|webp)
		convert -resize $MEDIUM -sharpen 1x0.5 "${FILE}[0]" "$SUBDIR/$M_FILE"
		;;

	    mpg|mpeg|mov|MOV|webm|mp4|avi)
		TMPDIR=$(mktemp -d -p.) || exit 1
		mplayer -vo jpeg:outdir="$TMPDIR" -ao null -zoom -frames 1 "${FILE}" >/dev/null 2>&1
		convert -resize $MEDIUM -sharpen 1x0.5 "${TMPDIR}/00000001.jpg" "$SUBDIR/$M_FILE"
		rm "$TMPDIR/00000001.jpg"
		rmdir "$TMPDIR"
		;;
	    
	    pef|PEF)
		FLIP=0
		if [ -e "$FILE.rotation" ] ; then
		    case $(< "$FILE.rotation") in
			180)  FLIP=3 ;;
			90)  FLIP=6 ;;
			270)  FLIP=5 ;;
		    esac
		fi
		dcraw -c -w -o1 -h -t $FLIP "$FILE" | convert -resize $MEDIUM -sharpen 1x0.5 ppm:- "$SUBDIR/$M_FILE"
		;;
	    
	    cr2|CR2)
		dcraw -c -w -o1 -h "$FILE" | convert -resize $MEDIUM -sharpen 1x0.5 ppm:- "$SUBDIR/$M_FILE"
		;;
	    
	    *)
		continue
		;;
	    
	esac
    fi

    [ -s "$SUBDIR/$S_FILE" ] || convert -resize $SMALL "$SUBDIR/$M_FILE" -sharpen 1x0.5 "$SUBDIR/$S_FILE"

    chmod --reference="$FILE" "$SUBDIR/$M_FILE"
    chmod --reference="$FILE" "$SUBDIR/$S_FILE"

    if [ -s "${FILE}.text" ] ; then
	FILETEXT="$(<"${FILE}.text")"
	ALTTEXT="$FILETEXT"
    else
	FILETEXT=
	ALTTEXT="${FILE}"
    fi
    ALTTEXT=$( echo "$ALTTEXT" | sed -e 's/</\&lt;/g' -e 's/>/\&gt;/g' -e 's/"/\&quot;/g' )

    if [ "$GALLERYCSS" ] ; then
	if [ "$FILETEXT" ] ; then
	    INSERT='class="txt"'
	else
	    INSERT='class="notxt"'
	fi
    else
	if [ "$FILETEXT" ] ; then
	    INSERT='border=3'
	else
	    INSERT='border=1'
	fi
    fi

    uriencode "$SUBDIR/$M_INDEX"
    echo -n "<a href=\"${URIENCODE}\">"
    uriencode "$SUBDIR/$S_FILE"
    echo "<img $INSERT alt=\"\" title=\"$ALTTEXT\" src=\"${URIENCODE}\" /></a>"

    (
	html_head "$THUMBCSS"
	echo '<body onLoad="document.getElementById('"'next'"').focus();">'
	echo -n "<p id=\"nav\">"
	PREV=$(( IDX - 1 ))
	NEXT=$(( IDX + 1 ))
	if [ $IDX -gt 0 ] ; then
	    uriencode "${FILES[${PREV}]}_m.html"
	    echo -n "<a href=\"${URIENCODE}\">&lt;&lt;</a>"
	else
	    echo -n "&lt;&lt;"
	fi
	uriencode "../$INDEX"
	echo -n " &nbsp; <a href=\"${URIENCODE}\">back</a> &nbsp; "
	if [ $NEXT -lt ${#FILES[*]} ] ; then
	    uriencode "${FILES[${NEXT}]}_m.html"
	    echo -n "<a id=\"next\" href=\"${URIENCODE}\">&gt;&gt;</a>"
	else
	    echo -n "&gt;&gt;"
	fi
	echo "</p>"
	uriencode "../$FILE"
	echo -n "<p id=\"pic\"><a href=\"${URIENCODE}\">"
	uriencode "$M_FILE"
	echo "<img alt=\"$FILE\" src=\"${URIENCODE}\" /></a></p>"

	if [ "$FILETEXT" ] ; then
	    if [ "$THUMBCSS" ] ; then
		echo "<div id=\"txt\">${FILETEXT}</div>"
	    else
		echo "<p id=\"txt\">${FILETEXT}</p>"
	    fi
	fi

	html_foot
	
    ) > "$SUBDIR/$M_INDEX"

    if [ $(( IDX % 10 )) == 9 ]; then
	status -n $(( IDX + 1 ))
    else
	status -n .
    fi

done

echo '</p>'
echo '<!--'
echo "PICTURES=${#FILES[*]}"
echo "SUBDIRS=$SUBDIRS"
echo "DATE=$(date +%Y%m%d%H%M%S)"
echo '-->'

html_foot

if [ ${#FILES[*]} == 0 ] ; then
    rmdir "$SUBDIR"
fi

status
