--- !ditz.rubyforge.org,2008-03-06/project 
name: photogallery
version: "0.3"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: photogallery
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.25
  status: :released
  release_time: 2008-07-08 20:06:23.172046 Z
  log_events: 
  - - 2008-06-29 20:47:10.200581 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
  - - 2008-07-08 20:06:23.172077 Z
    - Christian Garbs <mitch@cgarbs.de>
    - released
    - release v1.25
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.26
  status: :released
  release_time: 2008-07-13 17:05:07.699987 Z
  log_events: 
  - - 2008-07-08 20:10:12.125329 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
  - - 2008-07-13 17:05:07.700018 Z
    - Christian Garbs <mitch@cgarbs.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.27
  status: :released
  release_time: 2008-07-16 20:36:03.416935 Z
  log_events: 
  - - 2008-07-12 22:55:10.764922 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
  - - 2008-07-16 20:36:03.416967 Z
    - Christian Garbs <mitch@cgarbs.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.28
  status: :released
  release_time: 2008-12-27 21:28:31.172607 Z
  log_events: 
  - - 2008-07-16 20:27:14.557902 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
  - - 2008-12-27 21:28:31.172637 Z
    - Christian Garbs <mitch@cgarbs.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.29
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-12-27 22:10:03.795567 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
