# This workflow will execute the tests.
---
name: Run tests

on:
  push:
  pull_request:
    types: [opened]
  schedule:
    - cron: '29 5 4 * *'

jobs:
  run-tests:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install imagemagick
      - name: Execute tests
        run: |
          make test
